---
name: Marie
surname: Curie
position: "Principal Data Scientist"
address: "Lab for Scalable Mental Health"
profilepic: mcm_professional_shot.jpg
www: mcmullarkey.github.io
email: "mullarkey.mike@gmail.com"
twitter: mcmullarkey
github: mcmullarkey
linkedin: mariecurie
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "Michael is a clinical psychology PhD with expertise in data science and scaling mental health supports."
output: vitae::twentyseconds
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution,
  "PhD - Clinical Psychology", "2014-2020", "University of Texas at Austin",
  "MA - Clinical Psychology", "2011-2013", "American University",
  "BA - Psychology", "2008-2011", "American University"
) %>% 
  detailed_entries(Degree, Year, Institution)
```

## Brief Entries

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>% 
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year, 
    Desc
  )
```

# Skills

 * R (tidyverse, tidymodels, torch, shiny, rmarkdown)
 * Python (NumPy, Pandas, Scikit-learn, Keras, Flask)
 * SQL
 * Git
 * Time Series Forecasting

# Some stuff about me

 * I published [over 20 technical papers that have been cited nearly 1,000 times](https://scholar.google.com/citations?user=ncGnGSEAAAAJ&hl=en)

